In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
import time 
import warnings
warnings.filterwarnings('ignore')

In [2]:
driver=webdriver.Chrome(r"C:\Users\vorap\OneDrive\Desktop\chromedriver.exe")

In [3]:
driver.get('https://www.flipkart.com/')

In [4]:
sneakers=driver.find_element(By.CLASS_NAME,"_3704LK")
sneakers.send_keys("sneakers")

In [5]:
search=driver.find_element(By.CLASS_NAME,"L0Z3Pu")
search.click()

In [6]:
brand=[]
price=[]
product=[]

brands=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
for i in brands:
    b=i.text
    brand.append(b)
    
prices=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
for i in prices:
    p=i.text
    price.append(p)
    
products=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
for i in products:
    des=i.text
    product.append(des)

In [7]:
print(len(brand),len(price),len(product))

40 40 40

In [9]:
df=pd.DataFrame({'Brand':brand,'Price':price,'Product_Description':product})
df

,Brand,Price,Product_Description
0,SFR,₹249,2006 Trenddy Fashion Sporty Casuals Sneakers R...
1,BRUTON,₹399,Combo Pack Of 2 Casual Shoes Sneakers For Men
2,aadi,₹249,Synthetic Leather |Lightweight|Comfort|Summer|...
3,BIRDE,₹479,Combo Pack of 2 Casual Shoes Sneakers For Men
4,HIGHLANDER,₹599,Sneakers For Men
5,aadi,₹349,Sneakers For Men
6,World Wear Footwear,₹279,Latest Exclusive Affordable Collection of Tren...
7,BRUTON,₹399,Combo Pack Of 2 Casual Shoes Sneakers For Men
8,World Wear Footwear,₹399,Latest Exclusive Affordable Collection of Tren...
9,asian,₹714,"asian Thunder-01 White Color Change Sneakers,C..."
10,WHITE WALKERS,₹399,Stylish & Trending Outdoor Walking Comfortable...
11,BRUTON,₹399,2 Combo Sneaker Shoes Sneakers For Men
12,BIRDE,₹399,Premium Casual Shoes for Men Sneakers For Men
13,PUMA,"₹1,074",Player Sneakers For Men
14,BIRDE,₹499,Combo Pack Of 2 Casual Shoes Sneakers For Men
15,aadi,₹249,"Lightweight,Comfort,Summer,Trendy,Walking,Outd..."
16,BRUTON,₹399,Combo Pack Of 2 Casual Shoes Sneakers For Men
17,SFR,₹225,Sneakers For Men
18,World Wear Footwear,₹369,Latest Exclusive Affordable Collection of Tren...
19,Magnolia,₹349,Modern Trendy Sneakers boot Sneakers Sneakers ...
20,BRUTON,₹399,Combo Pack Of 2 Casual Shoes Sneakers For Men
21,RapidBox,₹549,Sneakers For Men
22,World Wear Footwear,₹249,Exclusive Affordable Collection of Trendy & St...
23,BRUTON,₹399,Combo Pack Of 2 Casual Shoes Sneakers For Men
24,Kraasa,₹299,Sneakers For Women
25,BRUTON,₹229,Lattest Sneakers Shoe Sneakers For Men
26,BRUTON,₹399,Combo Pack Of 2 Casual Shoes Sneakers For Men ...
27,kardam&sons,₹339,Fashionable Canvas Casual Partywear Outdoor Sn...
28,PUMA,"₹1,074",Player Sneakers For Men
29,Shozie,₹439,Sneakers For Women
30,BRUTON,₹399,Combo Pack Of 2 Casual Shoes Sneakers For Men
31,aadi,₹479,"Lightweight,Comfort,Summer,Trendy,Walking,Outd..."
32,aadi,₹499,Mesh |Lightweight|Comfort|Summer|Trendy|Walkin...
33,BRUTON,₹399,Combo Pack Of 4 Casual Shoes Loafer Shoes Snea...
34,BIRDE,₹649,Combo Pack of 2 Casual Shoe Sneakers For Men
35,BRUTON,₹229,Modern Trendy Shoes Sneakers For Men
36,BRUTON,₹399,2 Combo Sneaker Shoes Sneakers For Men
37,K- FOOTLANCE,₹479,Sneakers For Men
38,aadi,₹299,"Lightweight,Comfort,Summer,Trendy,Walking,Outd..."
39,asian,₹569,WATERPROOF-05cFULLBLACK Sneakers For Men